language: go
sudo: true

matrix:
  allow_failures:
    - go: master
  include:
    - os: linux
      go: 1.19.x
    - os: osx
      go: 1.19.x
    - os: windows
      go: 1.19.x
    - os: linux
      go: master

env:
  - CURRENT_CI_PROVIDER='Travis CI' GO111MODULE=on

before_install:
  # Setup directory for binaries
  - mkdir ./bin
  - export PATH=$PATH:$PWD/bin
  # golangci-lint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0

before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
  - go mod graph

script:
  # Just check gofmt on linux, it's the fastest builder
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
  # Lint code
  - golangci-lint run
  # Run Tests
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then bash <(curl -s https://codecov.io/bash); fi
