version: 2.1
jobs:
  build:
    working_directory: ~/cidetails
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: CURRENT_CI_PROVIDER=CircleCI go test -v ./...
